kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: redis
  labels:
    workload.user.cattle.io/workloadselector: redis
spec:
  ports:
    - name: tcp6379
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    workload.user.cattle.io/workloadselector: redis
  type: ClusterIP
