CREATE DATABASE mes_admin_device;
use mes_admin_device;
CREATE TABLE if not exists device_alarm_record (
begin_time datetime DEFAULT NULL COMMENT '产生时间',
device_id bigint DEFAULT NULL COMMENT '设备id',
acquisition_var_id bigint DEFAULT NULL COMMENT '采集变量id',
end_time datetime DEFAULT NULL COMMENT '结束时间',
id bigint ,
tenement_id bigint DEFAULT NULL COMMENT '租户id',
create_time datetime COMMENT '创建时间',
update_time datetime COMMENT '更新时间',
create_id bigint DEFAULT NULL COMMENT '创建人员id',
update_id bigint DEFAULT NULL COMMENT '更新人员id',
create_name varchar(50) COMMENT '创建人员名字',
update_name varchar(50) COMMENT '更新人员名字',
is_del tinyint(1) DEFAULT '0' COMMENT '是否已删除',
is_enable tinyint(1) DEFAULT '1' COMMENT '是否启用',
version int DEFAULT '1' COMMENT '版本',
alarm_val int DEFAULT NULL COMMENT '报警类型,12超上限,13超下线',
duration_sec bigint DEFAULT NULL COMMENT '持续时长'
)UNIQUE KEY(begin_time,device_id,acquisition_var_id)
PARTITION BY RANGE(begin_time)(
START ("2021-01-01") END ("2025-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(device_id) BUCKETS 8
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-60",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);
create table if not exists device_machine_sec_detail (
natureDateTime DATETIME ,
tenementId BIGINT ,
deviceId BIGINT ,
workshiftDate DATE,
date Date,
hour DateTime,
workshiftName VARCHAR(50) ,
eventCode CHAR(2) ,
onJobWorkerNum INT ,
onJobWorkerIdListStr varchar(65000),
runningSec INT ,
durationSec INT ,
workerOnJobDurationSec INT ,
programRunSec INT ,
cuttingSec INT 
)
Duplicate Key (natureDateTime,tenementId,deviceId) 
COMMENT "开机率-秒级粒度数据"
PARTITION BY RANGE(natureDateTime)(
START ("2021-01-01") END ("2025-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(tenementId,deviceId ) BUCKETS 8
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-200",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

create table if not exists device_machine_event_persist (
tenementId BIGINT ,
deviceId BIGINT ,
natureDateTime DATETIME ,
eventType int ,
workshiftDate DATE ,
workshiftName VARCHAR(50) ,
eventCode CHAR(2) ,
onJobWorkerNum INT ,
onJobWorkerIdListStr varchar(65000),
runningSec INT ,
durationSec INT ,
workerOnJobDurationSec INT ,
programRunSec INT ,
cuttingSec INT 
)
UNIQUE KEY  (tenementId,deviceId,natureDateTime,eventType) 
COMMENT "开机率事件持久化"
PARTITION BY RANGE(natureDateTime)(
START ("2021-01-01") END ("2025-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(tenementId,deviceId ) BUCKETS 8
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-200",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

CREATE TABLE `device_delta_collect` (
tenementId bigint DEFAULT NULL COMMENT '租户id',
reportDate date ,
reportTime datetime ,
deviceId bigint DEFAULT NULL COMMENT '设备id',
workshiftDate DATE COMMENT '班次日期',
workshiftName varchar(50) COMMENT '班次名称',
workshiftId bigint DEFAULT NULL COMMENT '班次id',
planId bigint DEFAULT NULL COMMENT '计划id',
productId bigint DEFAULT NULL COMMENT '产品id',
procedureId bigint DEFAULT NULL COMMENT '工序id',
locationId bigint DEFAULT NULL COMMENT '地点id',
orderId bigint DEFAULT NULL COMMENT '订单id',
shiftSnapshootId bigint DEFAULT NULL COMMENT '班次快照id',
stationGroupId  bigint DEFAULT NULL COMMENT '站点组id',
stationGroupName varchar(50) COMMENT '站点组名称',
stationId bigint DEFAULT NULL COMMENT '站点id',
stationName varchar(50) COMMENT '站点名称',
deviceName varchar(50) COMMENT '设备名称',
deviceWorksiteCode varchar(50) COMMENT '设备现场编号',
locationLevelStr varchar(500) COMMENT '地点名称',
workerListStr varchar(15000) COMMENT '人员集合字符串',
batchCode varchar(50) COMMENT '批次号',
productName varchar(50) COMMENT '产品名称',
productCode varchar(50) COMMENT '产品编号',
procedureName varchar(50) COMMENT '工序名称',
procedureCode varchar(50) COMMENT '工序编号',
productStandard varchar(50) COMMENT '产品规格',
tubingStandard varchar(50) COMMENT '管料规格',
productionSchedulingNum bigint DEFAULT NULL COMMENT '排产数量',
multiple DOUBLE DEFAULT NULL COMMENT '出产倍数',
coldScrapedNum int DEFAULT NULL COMMENT '冷模报废数量',
deltaJgs  int DEFAULT NULL COMMENT '加工数',
deltaBhgs int DEFAULT NULL COMMENT '不合格数',
jgjpSnap DECIMAL(19,4) DEFAULT NULL COMMENT '加工节拍快照',
jgsDeltaTimes int DEFAULT NULL COMMENT '加工数变化次数',
deltaJgjp DECIMAL(19 , 4) DEFAULT NULL COMMENT '加工节拍'

)UNIQUE KEY(tenementId, reportDate, reportTime,deviceId,workshiftDate,workshiftName,workshiftId,planId,productId,procedureId,locationId,orderId)
PARTITION BY RANGE(reportDate)(
    START ("2021-01-01") END ("2026-02-23") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(deviceId) BUCKETS 8
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-60",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

CREATE TABLE IF NOT EXISTS device_report_data(
        acquisition_time datetime DEFAULT NULL COMMENT 'acquisition_time',
        id VARCHAR(32) DEFAULT NULL COMMENT 'id',
        station_id VARCHAR(32) DEFAULT NULL COMMENT 'station_id',
        device_id VARCHAR(32) DEFAULT NULL COMMENT 'device_id',
        acquisition_type VARCHAR(32) DEFAULT NULL COMMENT 'acquisition_type',
        create_time datetime DEFAULT NULL COMMENT 'create_time',
        version VARCHAR(200) DEFAULT NULL COMMENT 'version',
        col_0 DOUBLE,
        col_1 DOUBLE,
        col_2 DOUBLE,
        col_3 DOUBLE,
        col_4 DOUBLE,
        col_5 DOUBLE,
        col_6 DOUBLE,
        col_7 DOUBLE,
        col_8 DOUBLE,
        col_9 DOUBLE,
        col_10 DOUBLE,
        col_11 DOUBLE,
        col_12 DOUBLE,
        col_13 DOUBLE,
        col_14 DOUBLE,
        col_15 DOUBLE,
        col_16 DOUBLE,
        col_17 DOUBLE,
        col_18 DOUBLE,
        col_19 DOUBLE,
        col_20 DOUBLE,
        col_21 DOUBLE,
        col_22 DOUBLE,
        col_23 DOUBLE,
        col_24 DOUBLE,
        col_25 DOUBLE,
        col_26 DOUBLE,
        col_27 DOUBLE,
        col_28 DOUBLE,
        col_29 DOUBLE,
        col_30 DOUBLE,
        col_31 DOUBLE,
        col_32 DOUBLE,
        col_33 DOUBLE,
        col_34 DOUBLE,
        col_35 DOUBLE,
        col_36 DOUBLE,
        col_37 DOUBLE,
        col_38 DOUBLE,
        col_39 DOUBLE,
        col_40 DOUBLE,
        col_41 DOUBLE,
        col_42 DOUBLE,
        col_43 DOUBLE,
        col_44 DOUBLE,
        col_45 DOUBLE,
        col_46 DOUBLE,
        col_47 DOUBLE,
        col_48 DOUBLE,
        col_49 DOUBLE,
        col_50 DOUBLE,
        col_51 DOUBLE,
        col_52 DOUBLE,
        col_53 DOUBLE,
        col_54 DOUBLE,
        col_55 DOUBLE,
        col_56 DOUBLE,
        col_57 DOUBLE,
        col_58 DOUBLE,
        col_59 DOUBLE,
        col_60 DOUBLE,
        col_61 DOUBLE,
        col_62 DOUBLE,
        col_63 DOUBLE,
        col_64 DOUBLE,
        col_65 DOUBLE,
        col_66 DOUBLE,
        col_67 DOUBLE,
        col_68 DOUBLE,
        col_69 DOUBLE,
        col_70 DOUBLE,
        col_71 DOUBLE,
        col_72 DOUBLE,
        col_73 DOUBLE,
        col_74 DOUBLE,
        col_75 DOUBLE,
        col_76 DOUBLE,
        col_77 DOUBLE,
        col_78 DOUBLE,
        col_79 DOUBLE,
        col_80 DOUBLE,
        col_81 DOUBLE,
        col_82 DOUBLE,
        col_83 DOUBLE,
        col_84 DOUBLE,
        col_85 DOUBLE,
        col_86 DOUBLE,
        col_87 DOUBLE,
        col_88 DOUBLE,
        col_89 DOUBLE,
        col_90 DOUBLE,
        col_91 DOUBLE,
        col_92 DOUBLE,
        col_93 DOUBLE,
        col_94 DOUBLE,
        col_95 DOUBLE,
        col_96 DOUBLE,
        col_97 DOUBLE,
        col_98 DOUBLE,
        col_99 DOUBLE,
        col_100 DOUBLE,
        col_101 DOUBLE,
        col_102 DOUBLE,
        col_103 DOUBLE,
        col_104 DOUBLE,
        col_105 DOUBLE,
        col_106 DOUBLE,
        col_107 DOUBLE,
        col_108 DOUBLE,
        col_109 DOUBLE,
        col_110 DOUBLE,
        col_111 DOUBLE,
        col_112 DOUBLE,
        col_113 DOUBLE,
        col_114 DOUBLE,
        col_115 DOUBLE,
        col_116 DOUBLE,
        col_117 DOUBLE,
        col_118 DOUBLE,
        col_119 DOUBLE,
        col_120 DOUBLE,
        col_121 DOUBLE,
        col_122 DOUBLE,
        col_123 DOUBLE,
        col_124 DOUBLE,
        col_125 DOUBLE,
        col_126 DOUBLE,
        col_127 DOUBLE,
        col_128 DOUBLE,
        col_129 DOUBLE,
        col_130 DOUBLE,
        col_131 DOUBLE,
        col_132 DOUBLE,
        col_133 DOUBLE,
        col_134 DOUBLE,
        col_135 DOUBLE,
        col_136 DOUBLE,
        col_137 DOUBLE,
        col_138 DOUBLE,
        col_139 DOUBLE,
        col_140 DOUBLE,
        col_141 DOUBLE,
        col_142 DOUBLE,
        col_143 DOUBLE,
        col_144 DOUBLE,
        col_145 DOUBLE,
        col_146 DOUBLE,
        col_147 DOUBLE,
        col_148 DOUBLE,
        col_149 DOUBLE,
        col_150 DOUBLE,
        col_151 DOUBLE,
        col_152 DOUBLE,
        col_153 DOUBLE,
        col_154 DOUBLE,
        col_155 DOUBLE,
        col_156 DOUBLE,
        col_157 DOUBLE,
        col_158 DOUBLE,
        col_159 DOUBLE,
        col_160 DOUBLE,
        col_161 DOUBLE,
        col_162 DOUBLE,
        col_163 DOUBLE,
        col_164 DOUBLE,
        col_165 DOUBLE,
        col_166 DOUBLE,
        col_167 DOUBLE,
        col_168 DOUBLE,
        col_169 DOUBLE,
        col_170 DOUBLE,
        col_171 DOUBLE,
        col_172 DOUBLE,
        col_173 DOUBLE,
        col_174 DOUBLE,
        col_175 DOUBLE,
        col_176 DOUBLE,
        col_177 DOUBLE,
        col_178 DOUBLE,
        col_179 DOUBLE,
        col_180 DOUBLE,
        col_181 DOUBLE,
        col_182 DOUBLE,
        col_183 DOUBLE,
        col_184 DOUBLE,
        col_185 DOUBLE,
        col_186 DOUBLE,
        col_187 DOUBLE,
        col_188 DOUBLE,
        col_189 DOUBLE,
        col_190 DOUBLE,
        col_191 DOUBLE,
        col_192 DOUBLE,
        col_193 DOUBLE,
        col_194 DOUBLE,
        col_195 DOUBLE,
        col_196 DOUBLE,
        col_197 DOUBLE,
        col_198 DOUBLE,
        col_199 DOUBLE,
        col_200 DOUBLE,
        col_201 DOUBLE,
        col_202 DOUBLE,
        col_203 DOUBLE,
        col_204 DOUBLE,
        col_205 DOUBLE,
        col_206 DOUBLE,
        col_207 DOUBLE,
        col_208 DOUBLE,
        col_209 DOUBLE,
        col_210 DOUBLE,
        col_211 DOUBLE,
        col_212 DOUBLE,
        col_213 DOUBLE,
        col_214 DOUBLE,
        col_215 DOUBLE,
        col_216 DOUBLE,
        col_217 DOUBLE,
        col_218 DOUBLE,
        col_219 DOUBLE,
        col_220 DOUBLE,
        col_221 DOUBLE,
        col_222 DOUBLE,
        col_223 DOUBLE,
        col_224 DOUBLE,
        col_225 DOUBLE,
        col_226 DOUBLE,
        col_227 DOUBLE,
        col_228 DOUBLE,
        col_229 DOUBLE,
        col_230 DOUBLE,
        col_231 DOUBLE,
        col_232 DOUBLE,
        col_233 DOUBLE,
        col_234 DOUBLE,
        col_235 DOUBLE,
        col_236 DOUBLE,
        col_237 DOUBLE,
        col_238 DOUBLE,
        col_239 DOUBLE,
        col_240 DOUBLE,
        col_241 DOUBLE,
        col_242 DOUBLE,
        col_243 DOUBLE,
        col_244 DOUBLE,
        col_245 DOUBLE,
        col_246 DOUBLE,
        col_247 DOUBLE,
        col_248 DOUBLE,
        col_249 DOUBLE,
        col_250 DOUBLE,
        col_251 DOUBLE,
        col_252 DOUBLE,
        col_253 DOUBLE,
        col_254 DOUBLE,
        col_255 DOUBLE,
        col_256 DOUBLE,
        col_257 DOUBLE,
        col_258 DOUBLE,
        col_259 DOUBLE,
        col_260 DOUBLE,
        col_261 DOUBLE,
        col_262 DOUBLE,
        col_263 DOUBLE,
        col_264 DOUBLE,
        col_265 DOUBLE,
        col_266 DOUBLE,
        col_267 DOUBLE,
        col_268 DOUBLE,
        col_269 DOUBLE,
        col_270 DOUBLE,
        col_271 DOUBLE,
        col_272 DOUBLE,
        col_273 DOUBLE,
        col_274 DOUBLE,
        col_275 DOUBLE,
        col_276 DOUBLE,
        col_277 DOUBLE,
        col_278 DOUBLE,
        col_279 DOUBLE,
        col_280 DOUBLE,
        col_281 DOUBLE,
        col_282 DOUBLE,
        col_283 DOUBLE,
        col_284 DOUBLE,
        col_285 DOUBLE,
        col_286 DOUBLE,
        col_287 DOUBLE,
        col_288 DOUBLE,
        col_289 DOUBLE,
        col_290 DOUBLE,
        col_291 DOUBLE,
        col_292 DOUBLE,
        col_293 DOUBLE,
        col_294 DOUBLE,
        col_295 DOUBLE,
        col_296 DOUBLE,
        col_297 DOUBLE,
        col_298 DOUBLE,
        col_299 DOUBLE,
        col_300 DOUBLE,
        col_301 DOUBLE,
        col_302 DOUBLE,
        col_303 DOUBLE,
        col_304 DOUBLE,
        col_305 DOUBLE,
        col_306 DOUBLE,
        col_307 DOUBLE,
        col_308 DOUBLE,
        col_309 DOUBLE,
        col_310 DOUBLE,
        col_311 DOUBLE,
        col_312 DOUBLE,
        col_313 DOUBLE,
        col_314 DOUBLE,
        col_315 DOUBLE,
        col_316 DOUBLE,
        col_317 DOUBLE,
        col_318 DOUBLE,
        col_319 DOUBLE,
        col_320 DOUBLE,
        col_321 DOUBLE,
        col_322 DOUBLE,
        col_323 DOUBLE,
        col_324 DOUBLE,
        col_325 DOUBLE,
        col_326 DOUBLE,
        col_327 DOUBLE,
        col_328 DOUBLE,
        col_329 DOUBLE,
        col_330 DOUBLE,
        col_331 DOUBLE,
        col_332 DOUBLE,
        col_333 DOUBLE,
        col_334 DOUBLE,
        col_335 DOUBLE,
        col_336 DOUBLE,
        col_337 DOUBLE,
        col_338 DOUBLE,
        col_339 DOUBLE,
        col_340 DOUBLE,
        col_341 DOUBLE,
        col_342 DOUBLE,
        col_343 DOUBLE,
        col_344 DOUBLE,
        col_345 DOUBLE,
        col_346 DOUBLE,
        col_347 DOUBLE,
        col_348 DOUBLE,
        col_349 DOUBLE,
        col_350 DOUBLE,
        col_351 DOUBLE,
        col_352 DOUBLE,
        col_353 DOUBLE,
        col_354 DOUBLE,
        col_355 DOUBLE,
        col_356 DOUBLE,
        col_357 DOUBLE,
        col_358 DOUBLE,
        col_359 DOUBLE,
        col_360 DOUBLE,
        col_361 DOUBLE,
        col_362 DOUBLE,
        col_363 DOUBLE,
        col_364 DOUBLE,
        col_365 DOUBLE,
        col_366 DOUBLE,
        col_367 DOUBLE,
        col_368 DOUBLE,
        col_369 DOUBLE,
        col_370 DOUBLE,
        col_371 DOUBLE,
        col_372 DOUBLE,
        col_373 DOUBLE,
        col_374 DOUBLE,
        col_375 DOUBLE,
        col_376 DOUBLE,
        col_377 DOUBLE,
        col_378 DOUBLE,
        col_379 DOUBLE,
        col_380 DOUBLE,
        col_381 DOUBLE,
        col_382 DOUBLE,
        col_383 DOUBLE,
        col_384 DOUBLE,
        col_385 DOUBLE,
        col_386 DOUBLE,
        col_387 DOUBLE,
        col_388 DOUBLE,
        col_389 DOUBLE,
        col_390 DOUBLE,
        col_391 DOUBLE,
        col_392 DOUBLE,
        col_393 DOUBLE,
        col_394 DOUBLE,
        col_395 DOUBLE,
        col_396 DOUBLE,
        col_397 DOUBLE,
        col_398 DOUBLE,
        col_399 DOUBLE,
        col_400 DOUBLE,
        col_401 VARCHAR(40),
        col_402 VARCHAR(40),
        col_403 VARCHAR(40),
        col_404 VARCHAR(40),
        col_405 VARCHAR(40),
        col_406 VARCHAR(40),
        col_407 VARCHAR(40),
        col_408 VARCHAR(40),
        col_409 VARCHAR(40),
        col_410 VARCHAR(40),
        col_411 VARCHAR(40),
        col_412 VARCHAR(40),
        col_413 VARCHAR(40),
        col_414 VARCHAR(40),
        col_415 VARCHAR(40),
        col_416 VARCHAR(40),
        col_417 VARCHAR(40),
        col_418 VARCHAR(40),
        col_419 VARCHAR(40),
        col_420 VARCHAR(40),
        col_421 VARCHAR(40),
        col_422 VARCHAR(40),
        col_423 VARCHAR(40),
        col_424 VARCHAR(40),
        col_425 VARCHAR(40),
        col_426 VARCHAR(40),
        col_427 VARCHAR(40),
        col_428 VARCHAR(40),
        col_429 VARCHAR(40),
        col_430 VARCHAR(40),
        col_431 VARCHAR(40),
        col_432 VARCHAR(40),
        col_433 VARCHAR(40),
        col_434 VARCHAR(40),
        col_435 VARCHAR(40),
        col_436 VARCHAR(40),
        col_437 VARCHAR(40),
        col_438 VARCHAR(40),
        col_439 VARCHAR(40),
        col_440 VARCHAR(40),
        col_441 VARCHAR(40),
        col_442 VARCHAR(40),
        col_443 VARCHAR(40),
        col_444 VARCHAR(40),
        col_445 VARCHAR(40),
        col_446 VARCHAR(40),
        col_447 VARCHAR(40),
        col_448 VARCHAR(40),
        col_449 VARCHAR(40),
        col_450 VARCHAR(40),
        col_451 VARCHAR(40),
        col_452 VARCHAR(40),
        col_453 VARCHAR(40),
        col_454 VARCHAR(40),
        col_455 VARCHAR(40),
        col_456 VARCHAR(40),
        col_457 VARCHAR(40),
        col_458 VARCHAR(40),
        col_459 VARCHAR(40),
        col_460 VARCHAR(40),
        col_461 VARCHAR(40),
        col_462 VARCHAR(40),
        col_463 VARCHAR(40),
        col_464 VARCHAR(40),
        col_465 VARCHAR(40),
        col_466 VARCHAR(40),
        col_467 VARCHAR(40),
        col_468 VARCHAR(40),
        col_469 VARCHAR(40),
        col_470 VARCHAR(40),
        col_471 VARCHAR(40),
        col_472 VARCHAR(40),
        col_473 VARCHAR(40),
        col_474 VARCHAR(40),
        col_475 VARCHAR(40),
        col_476 VARCHAR(40),
        col_477 VARCHAR(40),
        col_478 VARCHAR(40),
        col_479 VARCHAR(40),
        col_480 VARCHAR(40),
        col_481 VARCHAR(40),
        col_482 VARCHAR(40),
        col_483 VARCHAR(40),
        col_484 VARCHAR(40),
        col_485 VARCHAR(40),
        col_486 VARCHAR(40),
        col_487 VARCHAR(40),
        col_488 VARCHAR(40),
        col_489 VARCHAR(40),
        col_490 VARCHAR(40),
        col_491 VARCHAR(40),
        col_492 VARCHAR(40),
        col_493 VARCHAR(40),
        col_494 VARCHAR(40),
        col_495 VARCHAR(40),
        col_496 VARCHAR(40),
        col_497 VARCHAR(40),
        col_498 VARCHAR(40),
        col_499 VARCHAR(40),
        col_500 VARCHAR(40)
        )
                                DUPLICATE KEY (acquisition_time)
                                PARTITION BY RANGE(acquisition_time)(
 START ("2022-01-01") END ("2024-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(device_id) BUCKETS 8 
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-200",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

CREATE TABLE IF NOT EXISTS device_invalid_data(
        acquisition_time datetime DEFAULT NULL COMMENT 'acquisition_time',
        id VARCHAR(32) DEFAULT NULL COMMENT 'id',
        data VARCHAR(4096) DEFAULT NULL COMMENT 'param',
        create_time datetime DEFAULT NULL COMMENT 'create_time'
        )
                                DUPLICATE KEY (acquisition_time)
                                PARTITION BY RANGE(acquisition_time)(
 START ("2022-06-01") END ("2024-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(id) BUCKETS 8 
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-200",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

CREATE TABLE IF NOT EXISTS device_event_data(
        acquisition_time datetime DEFAULT NULL COMMENT 'acquisition_time',
        id VARCHAR(32) DEFAULT NULL COMMENT 'id',
        station_id VARCHAR(32) DEFAULT NULL COMMENT 'station_id',
        device_id VARCHAR(32) DEFAULT NULL COMMENT 'device_id',
        code INT DEFAULT NULL COMMENT 'code',
        create_time datetime DEFAULT NULL COMMENT 'create_time',
        version VARCHAR(200) DEFAULT NULL COMMENT 'version'
        )
                                DUPLICATE KEY (acquisition_time)
                                PARTITION BY RANGE(acquisition_time)(
 START ("2022-06-01") END ("2024-01-01") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(device_id) BUCKETS 8 
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.start" = "-200",
"dynamic_partition.end" = "60",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "8",
"replication_num" = "3"
);

