- hosts: k8s_master_node
  remote_user: root
  tasks:
  - name: linux env
    shell: systemctl stop firewalld && systemctl disable firewalld && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux && setenforce 0 && echo "net.bridge.bridge-nf-call-iptables = 1" > /etc/sysctl.conf && modprobe br_netfilter &&  sysctl -p /etc/sysctl.conf && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
    ignore_errors: yes
  - name: k8s env
    shell: swapoff -a && sysctl -w vm.swappiness=0 && sed -i '/swap/d' /etc/fstab && mkdir -p /etc/systemd/system/kubelet.service.d/
    ignore_errors: yes
  - name: crontab update
    shell: cat /var/spool/cron/root | grep ntpdate ||  echo "* */1 * * * /usr/sbin/ntpdate ntp.aliyun.com" > /var/spool/cron/root
  - name: copy-docker-ce.repo
    template: src={{ pwd }}/file/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo
  #- name: install k8s_组件
    #shell: yum install -y kubelet-1.28.2 kubeadm-1.28.2 kubectl-1.28.2 
    #shell: yum install -y docker-ce-20.10.12 docker-ce-cli-20.10.12  containerd.io ntp keepalived
    #ignore_errors: yes
  - name: copy k8s 1.28.2 rpm
    copy: src={{ pwd }}/file/rpm  dest=/opt/
  - name: install k8s1.28.2 docker
    shell: yum install -y /opt/rpm/docker/*
    ignore_errors: yes
  - name: install k8s1.28.2 k8s
    shell: yum install -y /opt/rpm/k8s/*
    ignore_errors: yes
  - name: install k8s1.28.2 tools
    shell: yum install -y /opt/rpm/tools/*
    ignore_errors: yes
  - name: 定义默认内核版本
    shell: grub2-set-default $(awk -F\' '$1=="menuentry " {print i++ "  " $2}' $( grep 5.16 /etc/grub* | awk -F ":" '{print $1}' | uniq ) | grep 5.16 | awk '{print $1}')
  - name: copy
    template: src={{ pwd }}/file/keepalived.conf_node dest=/etc/keepalived/keepalived.conf
  - name: start keepalived
    shell: systemctl restart keepalived && systemctl restart docker
  - name: copy-docker_daemon.json
    template: src={{ pwd }}/file/daemon.json dest=/etc/docker/daemon.json
  - name: enable 组件
    shell: systemctl enable docker.service && systemctl enable kubelet.service  && systemctl enable keepalived && systemctl enable  cri-docker
    # 修改/usr/lib/systemd/system/cri-docker.service ExecStart=/usr/bin/cri-dockerd --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.9 
  - name: docker启动替换配置cri-docker
    shell: sed -i 's|ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd://|ExecStart=/usr/bin/cri-dockerd --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.9|g' /usr/lib/systemd/system/cri-docker.service
  - name: copy-docker_config
    template: src={{ pwd }}/file/docker.service dest=/usr/lib/systemd/system/docker.service
  - name: restart 组件
    shell:  systemctl daemon-reload && systemctl restart docker && systemctl restart kubelet.service && systemctl restart  cri-docker
  - name: copy k8s_image
    copy: src={{ pwd }}/k8s_images  dest=/opt/
  - name: 导入k8s镜像
    shell: for i in `ls /opt/k8s_images/`; do docker load -i  /opt/k8s_images/$i ; done
  - name: copy token
    copy: src=/tmp/token  dest=/tmp/token  mode=755
  - name: 加入集群
    shell: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables  && bash /tmp/token 
  - name: k8s 端口范围开放1000-65535
    shell: sed -i "/    - --secure-port=6443/i\    - --service-node-port-range=1000-65535" /etc/kubernetes/manifests/kube-apiserver.yaml
#  - name: kubelet 资源限制保护
#    shell: cat /var/lib/kubelet/config.yaml | grep enforceNodeAllocatable || echo -e "enforceNodeAllocatable":"\n- pods\nkubeReserved":"  "#" 配置 kube 资源预留\n  cpu":" 500m\n  memory":" 2Gi\n  ephemeral-storage":" 2Gi\nsystemReserved":"  "#" 配置系统资源预留\n  memory":" 2Gi \nevictionHard":"  "#" 配置硬驱逐阈值\n  memory.available":" \"300Mi\"\n  nodefs.available":" \"10%\"\n " >> /var/lib/kubelet/config.yaml
