apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
  namespace: tidb-cluster
spec:
  configUpdateStrategy: RollingUpdate
  discovery: {}
  enableDynamicConfiguration: true
  enablePVReclaim: false
  helper:
    image: busybox:1.34.1
  imagePullPolicy: IfNotPresent
  pd:
    baseImage: pingcap/pd
    config: |
      [dashboard]
        internal-proxy = true
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
    service:
      type: NodePort
  pvReclaimPolicy: Retain
  ticdc:
    baseImage: pingcap/ticdc
    replicas: 3
  tidb:
    baseImage: pingcap/tidb
    config: |
      [log]
        [log.file]
          max-backups = 3

      [performance]
        tcp-keep-alive = true
    maxFailoverCount: 0
    replicas: 3
    service:
#      externalTrafficPolicy: Local
      type: NodePort
  tikv:
    baseImage: pingcap/tikv
    config: |
      log-level = "info"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      memory: 2Gi
      storage: 100Gi
  timezone: UTC
  tlsCluster: {}
  version: v5.3.0
