apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/used-by: end-user
  name: basic-tidb-nodeport
  namespace: tidb-cluster
spec:
  ports:
  - name: mysql-client
    nodePort: 4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: status
    nodePort: 10080
    port: 10080
    protocol: TCP
    targetPort: 10080
  selector:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  sessionAffinity: None
  type: NodePort
