---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s.kuboard.cn/name: ntp-exporter
  name: ntp-exporter
  namespace: ops
spec:
  selector:
    matchLabels:
      k8s.kuboard.cn/name: ntp-exporter
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: ntp-exporter
    spec:
      containers:
        - args:
            - '-ntp.server=cn.ntp.org.cn'
          image: 'sapcc/ntp-exporter:v2.1.0'
          imagePullPolicy: IfNotPresent
          name: ntp-exporter
          ports:
            - containerPort: 9559
              hostPort: 9559
              name: metrics
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

