# Source: prometheus-rabbitmq-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-exporter-prometheus-rabbitmq-exporter
  namespace: ops
  labels:
    app: prometheus-rabbitmq-exporter
    chart: prometheus-rabbitmq-exporter-1.2.0
    release: rabbitmq-exporter
    heritage: Helm
---
# Source: prometheus-rabbitmq-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter-prometheus-rabbitmq-exporter
  namespace: ops
  labels:
    app: prometheus-rabbitmq-exporter
    chart: prometheus-rabbitmq-exporter-1.2.0
    release: rabbitmq-exporter
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9419
      targetPort: publish
      protocol: TCP
      name: rabbitmq-exporter
  selector:
    app: prometheus-rabbitmq-exporter
    release: rabbitmq-exporter
---
# Source: prometheus-rabbitmq-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter-prometheus-rabbitmq-exporter
  namespace: ops
  labels:
    app: prometheus-rabbitmq-exporter
    chart: prometheus-rabbitmq-exporter-1.2.0
    release: rabbitmq-exporter
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-rabbitmq-exporter
      release: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: prometheus-rabbitmq-exporter
        release: rabbitmq-exporter
      annotations:
        {}
    spec:
      serviceAccountName: rabbitmq-exporter-prometheus-rabbitmq-exporter
      containers:
        - name: prometheus-rabbitmq-exporter
          image: "kbudde/rabbitmq-exporter:v0.29.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_URL
              value: "http://rabbitmq.dew-mid:15672"
            - name: RABBIT_USER
              value: "admin"
            - name: RABBIT_PASSWORD
              value: "ZAQ!2wsx"
            - name: PUBLISH_PORT
              value: "9419"
            - name: LOG_LEVEL
              value: "info"
            - name: RABBIT_CAPABILITIES
              value: "bert,no_sort"
            - name: INCLUDE_QUEUES
              value: ".*"
            - name: INCLUDE_VHOST
              value: ".*"
            - name: SKIP_QUEUES
              value: "^$"
            - name: SKIPVERIFY
              value: "false"
            - name: SKIP_VHOST
              value: "^$"
            - name: RABBIT_EXPORTERS
              value: "exchange,node,overview,queue"
            - name: OUTPUT_FORMAT
              value: "TTY"
            - name: RABBIT_TIMEOUT
              value: "30"
            - name: MAX_QUEUES
              value: "0"
          ports:
            - containerPort: 9419
              name: publish
          livenessProbe:
            httpGet:
              path: /
              port: publish
          readinessProbe:
            httpGet:
              path: /
              port: publish
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10002