#helm install --name prom-exporter --set "redisAddress=redis://redis7.apple-mid:6379" stable/prometheus-redis-exporter --namespace=apple-mid
# Source: prometheus-redis-exporter/templates/podsecuritypolicy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: redis-exporter-prometheus-redis-exporter
  namespace: ops
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    heritage: Helm
    release: redis-exporter
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
# Source: prometheus-redis-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ops
  name: redis-exporter-prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    release: "redis-exporter"
    heritage: "Helm"
---
# Source: prometheus-redis-exporter/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: redis-exporter-prometheus-redis-exporter
  namespace: ops
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    heritage: Helm
    release: redis-exporter
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [redis-exporter-prometheus-redis-exporter]
---
# Source: prometheus-redis-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redis-exporter-prometheus-redis-exporter
  namespace: ops
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    heritage: Helm
    release: redis-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-exporter-prometheus-redis-exporter
subjects:
- kind: ServiceAccount
  name: redis-exporter-prometheus-redis-exporter
---
# Source: prometheus-redis-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-prometheus-redis-exporter
  namespace: ops
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    release: redis-exporter
    heritage: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - name: redis-exporter
      port: 9121
      targetPort: exporter-port
      protocol: TCP
  selector:
    app: prometheus-redis-exporter
    release: redis-exporter
---
# Source: prometheus-redis-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-prometheus-redis-exporter
  namespace: ops
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.5.1
    release: redis-exporter
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-redis-exporter
      release: redis-exporter
  template:
    metadata:
      annotations:
        {}
      labels:
        app: prometheus-redis-exporter
        release: redis-exporter
    spec:
      serviceAccountName: redis-exporter-prometheus-redis-exporter
      containers:
        - name: prometheus-redis-exporter
          image: "oliver006/redis_exporter:v1.3.4"
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - name: exporter-port
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: redis://redis.redis:6379
          livenessProbe:
            httpGet:
              path: /
              port: exporter-port
          readinessProbe:
            httpGet:
              path: /
              port: exporter-port
          resources:
            {}