apiVersion: v1
kind: Namespace
metadata:
  name: minio
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: minio
  labels:
    k8s.kuboard.cn/name: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: minio
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: minio
    spec:
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio
      containers:
        - name: minio
          #image: minio/minio
          image: ghapp/minio/minio:latest
          args:
            - minio
            - server
            - /data
            - '--console-address'
            - ':9001'
          ports:
            - name: 9000tcp90001
              containerPort: 9000
              protocol: TCP
            - name: 9001tcp90011
              containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_PASSWORD
              value: zj88998!
            - name: MINIO_ROOT_USER
              value: minio
          resources: {}
          volumeMounts:
            - name: minio
              mountPath: /data
  strategy:
    type: Recreate

---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: minio
spec:
  ports:
    - name: 9000tcp90001-minio
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: 9001tcp90011-minio
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    workload.user.cattle.io/workloadselector: minio
  type: ClusterIP

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi


