#es默认配置es_host:es.elk-log，es_port 9200，注意修改container env
# 注意替换company的值
---
apiVersion: v1
data:
  syglfsall.yml: |
    name: "syglfsall"
    type: "frequency"
    index: "sygl-ilm-*"
    is_enabled: true
    num_events: 1
    realert:
      minutes: 5
    terms_size: 50
    timeframe:
      minutes: 5
    timestamp_field: "@timestamp"
    timestamp_type: "iso"
    use_strftime_index: false
    exponential_realert:
      hours: 1
    query_key:
      - server_name
    filter:
      - bool:
          filter:
            - match_all: {}
            - match_phrase:
                level: ERROR
    alert:
      - "post"

    http_post_url: "http://211.91.58.53:8081/api/altercenter/common-alert-entry/"
    http_post_static_payload:
      company: "p-ms"
      category: "log"
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:syglfs.yml: {}
        f:syglfsall.yml: {}
    manager: kubectl-create
    operation: Update
  name: elastalert-rules
  namespace: elk-log

---
apiVersion: v1
data:
  config.yaml: |
    rules_folder: /opt/elastalert/rules

    run_every:
      seconds: 30

    buffer_time:
      minutes: 15

    es_host: es.elk-log
    es_port: 9200

    writeback_index: elastalert_status

    alert_time_limit:
      days: 2
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.yaml: {}
    manager: kubectl-create
    operation: Update
  name: elastalert-config
  namespace: elk-log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: elastalert2
  name: elastalert2
  namespace: elk-log
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: elastalert2
  template:
    metadata:
      labels:
        name: elastalert2
    spec:
      containers:
        - env:
            - name: ES_HOST
              value: es.elk-log
            - name: ES_PORT
              value: '9200'
          image: 'sylinktest/elastalert2:1.0'
          imagePullPolicy: Always
          name: elastalert2
          volumeMounts:
            - mountPath: /opt/elastalert/rules/
              name: rules
            - mountPath: /opt/elastalert/config.yaml
              name: config
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: elastalert-rules
          name: rules
        - configMap:
            defaultMode: 420
            name: elastalert-config
          name: config

