apiVersion: v1
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://es:9200"]
    xpack.reporting.encryptionKey: 1234567890qwertyuiopasdfghjklzxc
    xpack.reporting.queue.indexInterval: week
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk-log

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: elk-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: ghapp/kibana:7.6.0
          #image: kibana:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5601
          volumeMounts:
          - mountPath: /usr/share/kibana/config
            name: kibana-config
      volumes:
      - configMap:
          defaultMode: 511
          name: kibana-config
          optional: false
        name: kibana-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: elk-log
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  type: NodePort
